// Code generated by "stringer -type=ColsType"; DO NOT EDIT.

package processor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VARCHAR-0]
	_ = x[INT-1]
	_ = x[FLOAT-2]
	_ = x[BOOL-3]
}

const _ColsType_name = "VARCHARINTFLOATBOOL"

var _ColsType_index = [...]uint8{0, 7, 10, 15, 19}

func (i ColsType) String() string {
	if i < 0 || i >= ColsType(len(_ColsType_index)-1) {
		return "ColsType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ColsType_name[_ColsType_index[i]:_ColsType_index[i+1]]
}
