// Code generated by "stringer -type=Ctype"; DO NOT EDIT.

package processor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TABLE-0]
	_ = x[DATABASE-1]
}

const _Ctype_name = "TABLEDATABASE"

var _Ctype_index = [...]uint8{0, 5, 13}

func (i Ctype) String() string {
	if i >= Ctype(len(_Ctype_index)-1) {
		return "Ctype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Ctype_name[_Ctype_index[i]:_Ctype_index[i+1]]
}
